export { default as Navbar } from './Navbar'
export { default as CryptoCurrencies } from './CryptoCurrencies'
export { default as CryptoDetails } from './CryptoDetails'
export { default as News } from './News'
export { default as About } from './About'
export { default as Homepage } from './Homepage'